image: conda/miniconda3:latest

stages:
  - test

test-job:
  tags:
    - ci.inria.fr
    - small
    - v2025
  stage: test
  script:
    - conda update -n base -c defaults conda
    - conda create -yq -n testing python=3
    - source activate testing
    - conda install anaconda::binutils
    - conda install git
    - conda install -yq numpy
    - conda install -yq scipy
    - conda install -c conda-forge pocl
    - conda install -c conda-forge pyopencl
    - pip install coverage
    - pip install -e .
    - coverage run -m unittest -v
    - coverage report
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
