[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["tractography"]

[project]
name = "tractography"
authors = [
	{name = "Samuel Deslauriers-Gauthier", email = "samuel.deslauriers-gauthier@inria.fr"},
	{name = "Romain Veltz", email = "romain.veltz@inria.fr"},
]
version = "0.2.10"
readme = "README.rst"
requires-python = ">=3.10"
dependencies = [
	"numpy>=2.0",
    "nibabel~=5.3",
    "scipy>=1.15",
    "siphash24~=1.7",
	"nimesh@git+https://gitlab.inria.fr/cronos/software/nimesh",
    "nimesh>=0.0.2",
    "pydantic~=2.10",
	"trimesh>=4.7",
    "mkdocs>=1.5",
    "coverage>=7.13.1,<8"
]

[project.scripts]
tractography = "tractography.cli:main"

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["osx-arm64", "osx-64", "linux-64"]

# Editable installs
[tool.pixi.pypi-dependencies]
tractography = { path = ".", editable = true }

# conda packages
[tool.pixi.dependencies]
pyopencl = "*"
pocl = "*"

[tool.pixi.tasks]
test = "python -c 'import tractography'"
unittest = "python -m unittest"
coverage = "coverage run -m unittest -v && coverage report && coverage xml && coverage html"
doc = "mkdocs gh-deploy"
