[build-system]
requires = ["setuptools", "pybind11>=2.13"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["tractography*"]

[tool.setuptools.package-data]
tractography = [
    "*.pyi",
    "resources/config/*.toml",
    "resources/kernels/*.cl",
    "resources/kernels/*/*.cl",
]

[project]
name = "tractography"
authors = [
	{name = "Samuel Deslauriers-Gauthier", email = "samuel.deslauriers-gauthier@inria.fr"},
	{name = "Romain Veltz", email = "romain.veltz@inria.fr"},
]
version = "0.3.0"
readme = "README.rst"
requires-python = ">=3.10"
dependencies = [
	"numpy>=2.0",
    "nibabel~=5.3",
    "meshio>=5.3",
    "scipy>=1.15",
    "scikit-learn>=1.5",
    "pyopencl>=2024",
    "siphash24~=1.7",
    "nimesh@git+https://gitlab.inria.fr/cronos/software/nimesh",
    "pydantic~=2.10",
	"trimesh>=4.7",
]

[project.scripts]
tractography = "tractography.cli:main"

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tool.pixi.dependencies]
cgal-cpp = ">=6.2"
python = ">=3.10"
pytest = ">=8"

[tool.pixi.pypi-dependencies]
tractography = { path = ".", editable = true }

[tool.pixi.tasks]
test = "python -m pytest"
