[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["tractography"]

[project]
name = "tractography"
authors = [
	{name = "Samuel Deslauriers-Gauthier", email = "samuel.deslauriers-gauthier@inria.fr"},
	{name = "Romain Veltz", email = "romain.veltz@inria.fr"},
]
version = "0.2.10"
readme = "README.rst"
requires-python = ">=3.10"
dependencies = [
    "numpy>=2.0",
    "nibabel~=5.3",
    "scipy>=1.15",
    "pyopencl>=2024",
    "siphash24~=1.7",
	"nimesh@git+https://gitlab.inria.fr/cronos/software/nimesh",
    "nimesh>=0.0.2",
    "pydantic~=2.10",
	"trimesh>=4.7"
]

[project.scripts]
tractography = "tractography.cli:main"

[tool.pixi.workspace]
channels = ["conda-forge", "anaconda"]
platforms = ["linux-64", "osx-arm64"]

# Editable installs
[tool.pixi.pypi-dependencies]
tractography = { path = ".", editable = true }

# conda packages
[tool.pixi.dependencies]
mkdocs = { version = "*", channel = "conda-forge" }
coverage = { version = "*", channel = "conda-forge" }

[tool.pixi.tasks]
test = "python -c 'import tractography'"
unittest = "python -m unittest"
coverage = "coverage run -m unittest -v && coverage report && coverage html"
doc = "mkdocs gh-deploy --config-file tractography/mkdocs.yml --force"

[tool.pixi.feature.cpu.dependencies]
binutils = { version = "*", channel = "anaconda" }
numpy = {version = "*", channel = "conda-forge" }
scipy = {version = "*", channel = "conda-forge" }
pocl = { version = "*", channel = "conda-forge" }
pyopencl = { version = "*", channel = "conda-forge" }

[tool.pixi.environments]
cpu = { features = ["cpu"], solve-group = "default" }
