[metadata]
name = tractography
version = 0.0.0
author = cronos
description = 'A Python package to perform diffusion MRI tractography.'
long_description = file: README.rst

[options]
packages = find:
python_requires = >=3.11
install_requires =
    numpy>=2.0
    nibabel>=5.0
    scipy>=1.14
    trimesh>=4.5
    pyopencl>=2024
    siphash24~=1.7

[options.entry_points]
console_scripts =
    tractography = tractography.cli:main
