# Default configuration file for diffusion tractography.
algorithm = "diffusion"


# The number of streamlines generated per batch.
batch_size = 50000

# The default step size. This is the value used internally for computation.
step_size = 0.001 # in seconds (or mm with 1mm/sec) 

# The default step size of the output streamlines.
save_at = 0.25 # in seconds (or mm with 1mm/sec) 

# The strength of the diffusion term. A value of 2.0 given the FOD as the
# stationary solution.
noise_variance = 2.0

inverse_curvature = 0.5

[streamline]
length.minimum = 10.0  # in mm
length.maximum = 300.0 # in mm
